export const FETCH_COUNCILORS_START = 'councilor/FETCH_COUNCILORS_START';
export const FETCH_COUNCILORS_ERROR = 'councilor/FETCH_COUNCILORS_ERROR';
export const RECEIVE_COUNCILORS = 'player/RECEIVE_COUNCILORS';
